### PR TITLE
Feature/1131 status labels

### PR DESCRIPTION
**Pull request by xak**
Closes sap/fundamental#1131

Adds a container to each page with a status label and the version first released and last updated.

#### Test

* Affects every foundation, layout, and component page on the site — https://deploy-preview-1135--fundamental.netlify.com/index.html
* Status labels should match https://github.com/SAP/fundamental/wiki/Component-Versions-and-Status

#### Changelog

**New**

* Adds `id` to each components meta data in docs file, used to look up the version data
* Adds `data/versions.yml` file to manage the data. This is the only file that needs to be updated when bumping up versions. https://github.com/SAP/fundamental/blob/84aa320f2d4ecf417123b9914da62fc612f4e8be/docs/_data/versions.yml
* Adds `data/status.yml` file to look up strings. https://github.com/SAP/fundamental/blob/84aa320f2d4ecf417123b9914da62fc612f4e8be/docs/_data/status.yml

Format: 
```
ui:
  status: deprecated
  since: 1.0.0
  updated:
  remove: 1.7.0
```

Status label can be new, stable, review, deprecated, experimental. If deprecated, use remove for target removal release.

screen shot 2018-12-19 at 4 51 36 pm
screen shot 2018-12-19 at 4 51 52 pm

* Added library version number to the top nav as a reference when viewing individual component pages

**Changed**

* N/A

**Removed**

* Removed several orphaned pages for deprecated components, like cards and toolbar

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit 84aa320f2d4ecf417123b9914da62fc612f4e8be

https://deploy-preview-1135--fundamental.netlify.com

**Comment by saadmhybris** [comment]
@xak `action-bar` does not have any status information? it's not mentioned in the [component version and status page](https://github.com/SAP/fundamental/wiki/Component-Versions-and-Status#components) either. The PR looks good otherwise.

**Comment by xak** [comment]
OK, the status is on the wiki ... https://github.com/SAP/fundamental/wiki/Component-Versions-and-Status#floorplan-elements

I'll update the PR.

**Comment by xak** [comment]
@saadmhybris Ready now!

**Pull request merged**
