### PR TITLE
chore: Alert component update and IE11 fixes

### PR DESCRIPTION
**Pull request by eboyer**
Closes sap/fundamental#1332
Closes sap/fundamental#1259
Closes sap/fundamental#1260
Closes sap/fundamental#1261
Closes sap/fundamental#1262

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit bd7e95828d7f9bafb5d8f2143e1bca17ecafd0ca

https://deploy-preview-1359--fundamental.netlify.com

**Comment by droshev** [comment]
The button border is outside of the alert border:
Screen Shot 2019-03-27 at 11 40 57 AM

**Comment by eboyer** [comment]
> The button border is outside of the alert border:
> Screen Shot 2019-03-27 at 11 40 57 AM

I believe that is logged here: https://github.com/SAP/fundamental/issues/1277

**Comment by droshev** [comment]
how about adding an example with wrapped text like in the design spec:
Screen Shot 2019-03-27 at 11 45 07 AM

**Comment by bcullman** [comment]
@eboyer - that is unrelated to #1277

**Comment by bcullman** [comment]
looks like this lines up on the first alert (the information one) but fails on the remaining ones

image

This is because the info one has a <href> link that is causing the container to be a min height of 20px. The other alerts don't have this link, causing them to be a height of 19px

This is pretty fragile.

**Comment by eboyer** [comment]
@bcullman ~ For the color of the alert, this is solved in the "color update" PR. There was just an incorrect value in the color set. 

For the height issues, what do you think about having a min-height on our alerts?

**Comment by bcullman** [comment]
@eboyer - The problem is that you are using a bottom border for the text underline, and then setting the display to inline-block, which then causes the render engine to take the text's entire surrounding box model into consideration. you can set a min-height and viola you fixed it in this *one* instance.

This is a bad idea, and we will continue to be plagued by various places where stuff is off by "just one pixel" because of it. 

* Have a paragraph of text with a link on the 3rd line? Line 3 will be off (and look odd). 
* Have some text in various HTML table cells valign middle, and only one cell in the row has a link? That one won't align. 

This will never end. There are 2 ways of fixing this.

1) Change the display to inline. Doing so you will lose the box model padding (and likely the reasoning why you choose to use bottom border to begin with.
2) Use good-old `text decoration: underline`

**Comment by eboyer** [comment]
@bcullman ~ I don't disagree with what you've said. But having a min-height of `20px` as a standard "one line alert" had more thought behind it than trying to avoid a 1px discrepancy. More of a standard default for that pattern.

**Comment by LeoT7508** [comment]
Hey guys, Im not sure if Im not following correctly, but Alert/Message strips should be 40px tall for one line messages and 60px tall for two line messages.

**Comment by eboyer** [comment]
@LeoT7508 ~ Yeah you're right. I mis-spoke. We're looking at numbers like 38/39/40 in the discrepancies.

**Comment by bcullman** [comment]
Given these components can be used in responsive web design, and in applications where localization can cause a 1 line piece of text to go to 2 lines in German, we cannot pass a height value to this component depending on how many lines of text are provided. Instead, we should be working with text that has a line height of 20px. 

Which we do. 👍 

However, the same problem will remain - if we set the min-height to 40px, and then have 2 lines of content that contains a link, it will kick the overall height to 61px.

**Comment by droshev** [comment]
@eboyer @bcullman How about we target only the colors(for IE) of the alerts in this PR and the height, examples with multiple lines we do in a separate PR targeting only that issue?
It would be cleaner if we keep 1:1 relationship of issue:PR

**Comment by bcullman** [comment]
@droshev - I am fine with tackling the color here. But if you set the min-height here, you will further obscure the deeper problem I laid out above.

**Pull request merged**
