### PR TITLE
#741 type updates — scale, weights and margins

### PR DESCRIPTION
**Pull request by xak**
Closes sap/fundamental#741

The type specs have been updated to remove some smaller sizes and add a few other mid-sizes. This is a more accessible hierarchy that still gives designers flexibility.

#### Test

* http://localhost:3030/pages/styles
* http://localhost:4000/foundation/type.html
* http://localhost:4000/guides/design-system-utilities.html
* http://localhost:3030/pages/text

#### Changelog

**New**

* Adds bottom margin values to `fd-type` map

* Create type functions to look up individual properties in   `functions/_type.scss`
  - `@function fd-font-size($size: "0")`
  - `@function fd-line-height($size: "0")`
  - `@function fd-font-weight($size: "0")`
  
* Separated mixins into `mixins/_type.scss`
  - `@mixin fd-type($size: "0", $weight: "normal")`
  - `@mixin fd-weight($weight: reg)`

* The `fd-type()` mixin now returns the bottom margin value

* Started a new text spec sheet for testing — http://localhost:3030/pages/text

**Changed**

* Updates `fd-type` map values to insert two new values, remove two and shift the others
  - `6` is the old `5`
  - `5` is a new value
  - `4` is the old `3`
  - `3` is a new value
  - `-1` is the old `-2`
  - `-2`, `-3` have been removed

* Shifts type from `3` to `4`
  - http://localhost:3030/action-bar
  - http://localhost:3030/pages/section
  
* Changes `-2` and `-3` to `-1`
  - http://localhost:3030/badge
  - http://localhost:3030/button
  - http://localhost:3030/calendar
  - http://localhost:3030/identifier
  - http://localhost:3030/inline-help
  - http://localhost:3030/label
  - http://localhost:3030/mega-menu
  - http://localhost:3030/menu
  - http://localhost:3030/side-nav
  - http://localhost:3030/table
  - http://localhost:3030/tag
  - http://localhost:3030/tree
  - http://localhost:3030/panel

* The `$fd-weights` map is updated to only include `light`, `normal`, and `bold`

  

**Removed**

* Addt'l type params `font-family`, `weight` and `transform`
  - The `fd-type` map now only defines the size and line-height
  - The `fd-type` mixin now only accepts size and `weight`
  
> NOTE: #745 will provide variety in sizes and weights with more convenient mixins

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit 939c5fc4bb11272233f47a7f65562956cfdb9ca5

https://deploy-preview-775--fundamental.netlify.com

**Comment by saadmhybris** [comment]
@xak 

- [Type page](http://localhost:4000/foundation/type.html) still shows old type scale. Looks like documentation updates are part of this ticket. 
- There are some rendering issues with the [sections test page](http://localhost:3030/pages/section), but these may be preexisting issues. 
- Couple of SCSS compilation errors when you run `gulp` to start the docs site
```
WARNING: Invalid $shade of `4` in the map $type of `action`. Valid $shade values are 1, 2, 3. Returning `black`.
         on line 11 of docs/scss/_docs-functions.scss, in function `docs-color`
         from line 1 of docs/scss/_docs-utils.scss
         from line 4 of docs/scss/docs-all.scss

WARNING: Invalid $shade of `4` in the map $type of `action`. Valid $shade values are 1, 2, 3. Returning `black`.
         on line 11 of docs/scss/_docs-functions.scss, in function `docs-color`
         from line 153 of docs/scss/_docs-home.scss
         from line 11 of docs/scss/docs-all.scss
```

**Comment by xak** [comment]
I addressed the bottom margin (#173) and font weights (#746) issues along with this one.

**Comment by saadmhybris** [comment]
@xak 

Looks like there are more font-family options available, but not defined in [72.scss](https://github.com/SAP/fundamental/blob/feature/741/scss/fonts/72.scss). Is there a reason why we are not adding support for `condensed`, condensed-bold` and `black`?

**Pull request closed without merging**
