### PR TITLE
docs: tablet mode paddings

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Fixes the padding on the landing page for tablet sizes

### CODE REVIEW

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey stefano,
Thanks for doing this quick :)

I have one comment:

1. The arrows are the wrong size, and aren't properly aligned with the tablet grid.
Screen Shot 2020-11-04 at 9 21 38 AM

**Comment by stefanoScalzo** [comment]
> Hey stefano,
> Thanks for doing this quick :)
> 
> I have one comment:
> 
> 1. The arrows are the wrong size (should be like desktop/48 px)
>    Arrows are also way below the text and aren't lining up with the side margins (for the tablet grid).
> 
> Screen Shot 2020-11-04 at 9 21 38 AM

fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Great!

Could you just remove the awkward line break and left-align the text for the intro sentence? It looks awkward and should be consistent with the other sections.
Screen Shot 2020-11-04 at 1 52 23 PM

**Comment by stefanoScalzo** [comment]
> Great!
> 
> Could you just remove the awkward line break and left-align the text for the intro sentence? It looks awkward and should be consistent with the other sections.
> Screen Shot 2020-11-04 at 1 52 23 PM

Fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Just noticed this... the arrows are located at the edge of the screen like mobile is designed, they should be aligned with the margins like in the sketch doc:
Screen Shot 2020-11-04 at 5 08 58 PM

**Comment by stefanoScalzo** [comment]
> Just noticed this... the arrows are located at the edge of the screen like mobile is designed, they should be aligned with the margins like in the sketch doc:
> Screen Shot 2020-11-04 at 5 08 58 PM

I fixed the padding on the arrows, since blogs are also getting refactored completely it is normal that the grid isn't completely aligned with them yet and will be in another pr

**Review by jessmetivier — CHANGES_REQUESTED** [review]
The arrows are now misplaced when in mobile view. They were perfect before.
Screen Shot 2020-11-10 at 9 39 41 AM

When I noted the issues with the arrows, I was just talking about the tablet version.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Everything looks great! There's just one weird thing that I noticed it:

The spacing is off between the Libraries and 
Screen Shot 2020-11-13 at 12 53 43 PM

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hi Stefano,

It's almost good to go. There's just an issue with the arrows, it looks like one side has more padding/less margin than the other.
Screen Shot 2020-11-17 at 12 06 21 PM

**Comment by stefanoScalzo** [comment]
> Hi Stefano,
> 
> It's almost good to go. There's just an issue with the arrows, it looks like one side has more padding/less margin than the other.
> Screen Shot 2020-11-17 at 12 06 21 PM

fixed

**Review by jessmetivier — APPROVED** [review]
C'est bon!

**Review by jessmetivier — APPROVED** [review]

**Review by droshev — APPROVED** [review]

**Pull request merged**
