### PR TITLE
#504 toggle updates 

### PR DESCRIPTION
**Pull request by saadmhybris**
Closes sap/fundamental#504

{{short description}}

#### Test

* http://localhost:3030/toggle

#### Changelog

**New**

nothing

**Changed**

* toggle colors update

**Removed**

* nothing

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit 0f6a4e8f2d7a96dbee8a47a5649de188014916d4

https://deploy-preview-613--fundamental.netlify.com

**Comment by LeoT7508** [comment]
@saadmhybris 

screen shot 2018-08-10 at 10 00 01 am

**Comment by LeoT7508** [comment]
@saadmhybris 

This is good to go.

**Comment by saadmhybris** [comment]
This is ready for code review.

**Pull request merged**
