### PR TITLE
#561 Adjusts dropdown to be 100% width

### PR DESCRIPTION
**Pull request by eboyer**
Closes sap/fundamental#561

Adjusts `dropdown` to be `width: 100%`. It will be up to the wrapping containers around it to define the width it should be to avoid changing sizes depending on the selected option.

#### Test

* http://localhost:4000/components/dropdown.html

#### Changelog

**Changed**

* http://localhost:4000/components/dropdown.html

### CODE REVIEW

**Comment by saadmhybris** [comment]
@eboyer 

screen shot 2018-07-24 at 11 28 48 am
Dropdowns in test page looks weird.

**Comment by saadmhybris** [comment]
also has conflicts now.

**Comment by eboyer** [comment]
@saadmhybris ~ hmmm, let me check that out. all CSS is compiled alright?

**Comment by saadmhybris** [comment]
yes. documentation page looked good.

**Comment by eboyer** [comment]
@saadmhybris ~ right.

**Comment by saadmhybris** [comment]
any updates?

**Comment by eboyer** [comment]
@saadmhybris ~ I pushed this commit earlier today already. It looks like it was squashed in a rebase so it doesn't appear on its own, but these dropdowns should be fixed.

**Pull request merged**
