### PR TITLE
docs: footer

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Closes sap/fundamental#1573
this pr will add the new footer, page and footer at size xl will be targeted in another pr

### CODE REVIEW

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey Stefano,

Thanks for the changes, and the link hover looks great!

But it still doesn't look right, when I look at the design... the distances are wider between columns, and the logo for the XL is larger (I see the width is 70px when at 1500px screen width, and it should be 96px got XL and 82px for L).

_Awkward white space on the right side of the screen, which becomes way worse as the screen widens_
Screen Shot 2020-11-09 at 9 53 42 AM

1. Please correct the logo sizes at each screen size (if they aren't of course, so far I just checked the XL and L)
2. Make the columns 180px apart for L and XL
3. Make the bottom-padding of the footer 44px for all

One thing I missed:

4. Please change the color of the separator to F0F0F0, it was that color for the mobile and I forgot to change the color of all of them from FFFFFF.

Thank you! :)

**Comment by stefanoScalzo** [comment]
Fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
I'm going to let you be the judge here, does this look right?

The design:
Screen Shot 2020-11-10 at 9 55 06 AM

Your implementation:
Screen Shot 2020-11-10 at 9 55 19 AM

**Comment by stefanoScalzo** [comment]
fixed!

**Review by jessmetivier — CHANGES_REQUESTED** [review]
The margin is fixed, but I still think the distance between the text is not quite right... Are you sure it's 180px apart?

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Please change the separator color to F0F0F0, it's still white for all of them: 
Screen Shot 2020-11-10 at 3 40 26 PM

**TABLET VERSION**
I just noticed the closeness of the separator and the text underneath, I just changed the design a little so that it can look better in implementation. The separator should have 10px padding on the top and bottom now
Screen Shot 2020-11-10 at 3 41 21 PM

**Comment by stefanoScalzo** [comment]
> Please change the separator color to F0F0F0, it's still white for all of them:
> Screen Shot 2020-11-10 at 3 40 26 PM
> 
> **TABLET VERSION**
> I just noticed the closeness of the separator and the text underneath, I just changed the design a little so that it can look better in implementation. The separator should have 10px padding on the top and bottom now
> Screen Shot 2020-11-10 at 3 41 21 PM

So the color is the right one, you need to look at the border, not the color, color corresponds to text. I fixed the paddings

**Review by jessmetivier — APPROVED** [review]
Great job!

**Review by droshev — APPROVED** [review]

**Comment by jessmetivier** [comment]
Any way to just put max-width padding for just the XL size?
Screen Shot 2020-11-18 at 2 17 59 PM

**Comment by stefanoScalzo** [comment]
> Any way to put max-width padding for just the XL size?
> Screen Shot 2020-11-18 at 2 17 59 PM

I can do this in the XL PR

**Pull request merged**
