### PR TITLE
Docs: xl size

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Add xl modification with all current documentation
Touches up some desktop styling

### CODE REVIEW

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey stefano it looks really good, just a couple things:
- The images look very big in the Design section, are you sure they match the designs?
- The design section outer margins also look larger than the other sections, while the testimonial section is smaller than the rest (making the content look wider). **Let's talk about this over a call.**
- At the very bottom, the content should have 48px padding between them (Copyright / Privacy etc)

Can we add a max-width for the footer container so it aligns with the rest of the sections?
Although it's very equally spaced out, it looks completely off grid right now.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
hey stefano!

As discussed, we just need to fix:
- the margins in the About section so that they are 55px apart.
- the font size and weights for the H3 headers in the Design section (refer to design for specs).

**Comment by stefanoScalzo** [comment]
> hey stefano!
> 
> As discussed, we just need to fix:
> 
> * the margins in the About section so that they are 55px apart.
> * the font size and weights for the H3 headers in the Design section (refer to design for specs).

fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey stefano,

The design section looks great!
 
The regular text in these sections need to be adjusted though, starting with:

Screen Shot 2020-12-02 at 4 13 14 PM
This regular text should be 20px

Screen Shot 2020-12-02 at 4 14 37 PM
Should be 22px

**Comment by stefanoScalzo** [comment]
> Hey stefano,
> 
> The design section looks great!
> 
> The regular text in these sections need to be adjusted though, starting with:
> 
> Screen Shot 2020-12-02 at 4 13 14 PM
> This regular text should be 20px
> 
> Screen Shot 2020-12-02 at 4 14 37 PM
> Should be 22px

fixed font sizes for xl

**Review by droshev — CHANGES_REQUESTED** [review]
there is something wrong with the PR - it addess 134,000+ lines of code

**Comment by droshev** [comment]
This PR cannot be merged in this state - closing it for now

**Pull request closed without merging**
