### PR TITLE
Docs: community section

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Closes sap/fundamental#1575
Add email and linked in
fix layout

### CODE REVIEW

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey! It's looking good with the new icons!

I'm not sure why but it's not rendering the linkedin icon:
Screen Shot 2020-11-04 at 9 37 36 AM

And the link text underneath is too small for the L screen size, I would keep it at 20px. I'll be designing the XL today!

**Comment by stefanoScalzo** [comment]
> Hey! It's looking good with the new icons!
> 
> I'm not sure why but it's not rendering the linkedin icon:
> Screen Shot 2020-11-04 at 9 37 36 AM
> 
> And the link text underneath is too small for the L screen size, I would keep it at 20px. I'll be designing the XL today!

It didn't get added to the staged changes, should be good now

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey, looking good.

Just two things — in mobile view:

1. The text sizes are too large in the Community section, they need to be aligned with the others.
Screen Shot 2020-11-04 at 3 20 15 PM

2. The icons are too far apart because I think you're aligning them with the margins. These are grouped in the center and have a 44px padding between each other on a 320px wide screen (the basis from the design).
Screen Shot 2020-11-04 at 3 22 28 PM

**Comment by jessmetivier** [comment]
Icons look great, just tested it on my phone!

But the header text and regular text is still too large compared to the other sections.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Please see comment

**Comment by stefanoScalzo** [comment]
fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Almost done, I just notice that the icons are huge at 1400px and then go back to normal size — could we fix that?

**Review by jessmetivier — APPROVED** [review]
W00t!

**Review by droshev — APPROVED** [review]

**Pull request merged**
