### PR TITLE
feat: toggle updates

### PR DESCRIPTION
**Pull request by saad-mo**
Closes sap/fundamental#969

- Updated toggle to the latest design
- added `compact` size option
- added `label` modifier to support inline label 
- added `semantic` modifier for the semantic version of the toggle with colors and icon
- updated documentation to reflect the newly available options 

Screen Shot 2019-05-29 at 3 45 29 PM
Screen Shot 2019-05-29 at 3 45 49 PM
Screen Shot 2019-05-29 at 3 45 34 PM
Screen Shot 2019-05-29 at 3 45 54 PM

#### Test

* http://localhost:3030/toggle
* http://127.0.0.1:4000/components/toggle.html

#### Changelog

**New**

* `compact` size modifier
* `label` modifier
* `semantic` modifier

**Changed**

* refactored scss to support default width extension if the labels need to be longer than three characters 

**Removed**

nothing. this is a non-breaking change with no changes to existing markup or modifiers

### CODE REVIEW

**Comment by saad-mo** [comment]
@LeoT7508 for your review - https://deploy-preview-1466--fundamental.netlify.com/components/toggle.html

**Comment by droshev** [comment]
I am fine with putting an icon inside the toggle, but what about the text inside. In English we have short words `ON` and `OFF`, but in other languages this is longer, which won't fit.
@jeannewalters @LeoT7508 what do you think?

**Comment by jeannewalters** [comment]
@droshev I would suggest always putting the value such as on/off should be outside to account for longer translations.

**Comment by LeoT7508** [comment]
@jeannewalters @droshev 

This is something you would have to file under "get feedback from GD". At this point this is how they are suggesting we do it. There isn't a design for the label outside.

**Comment by jeannewalters** [comment]
@LeoT7508 I just checked the latest Sketch file (v. 1.66) and they still have a version with the label on the outside.

**Comment by LeoT7508** [comment]
@jeannewalters 

Ah yes, I missed that, thanks for the correction. 

@saad-mo  i'll put that in the design sheet quickly.

**Comment by saad-mo** [comment]
@droshev, @jeannewalters - If you look at the [documentation page](https://deploy-preview-1466--fundamental.netlify.com/components/toggle.html) I have a note on how you can increase the width of the toggle if you need to support more than 3 characters. I feel we need to provide this version as it is part of the design specs from GD. 

Toggles always supported a label on the outside. I'll update the docs page to show this along with leo's updates.

**Comment by droshev** [comment]
It would be useful to document that we recommend labeling the text next to the `toggle`. you write that for 1-3 latin letters then can put it inside.

**Comment by saad-mo** [comment]
@droshev @jeannewalters @LeoT7508 

Documentation page has been updated with the latest text from @jeannewalters please review. 

as recommended, the documentation does not include the toggle with labels on the inside. we can leave it in the code if someone requests it down the line.

**Comment by saad-mo** [comment]
these changes have been applied to fundamental-styles as well

**Pull request merged**
