### PR TITLE
fix:  Fixed list item misalignment issue

### PR DESCRIPTION
**Pull request by JYSW380**
Closes sap/fundamental#1316

### CODE REVIEW

**Comment by ChristianKienle** [comment]
Just one question: How can this be approved even though there are build errors? Or are failing builds okay in this repo?

**Comment by saad-mo** [comment]
@droshev can this be merged now?

**Comment by saad-mo** [comment]
> Just one question: How can this be approved even though there are build errors? Or are failing builds okay in this repo?

maybe the approved checked the changes locally. we can't merge PR until all the build errors are fixed.

**Comment by InnaAtanasova** [comment]
The merge button is disabled if there are build errors

**Comment by saad-mo** [comment]
@droshev pls unblock this PR so that it can be merged

**Comment by droshev** [comment]
@saad-mo this is issue is still in progress. I would even take the PR back until it is fixed in styles

**Pull request merged**
