### PR TITLE
chore: update package-lock.json to fix axios vulnerability

### PR DESCRIPTION
**Pull request by saad-mo**
Updated package-lock.json as suggested by the security alert - https://github.com/SAP/fundamental/network/alert/package-lock.json/axios/open

### CODE REVIEW

**Comment by greg-a-smith** [comment]
@saad-mo How did this file get updated?  Was it manually edited?  Was it re-running `npm install`?  Was the file deleted and then regenerated with `npm install`?  Typically, this file shouldn't change unless there is a change in `package.json`.

**Comment by jbadan** [comment]
@greg-a-smith and @saad-mo 
These need to be merged and released before we can fix the problem in our repo: https://github.com/BrowserSync/browser-sync/pull/1697 
https://github.com/github-tools/github/issues/565

then update github-assistant with new github-api, release, update all fundamental-* packages.

**Comment by j-rewerts** [comment]
GitHub tools has released version 3.2.2 with this vulnerability fixed.

**Comment by jbadan** [comment]
@j-rewerts Thanks for following up! Feel free to open a pr :)

**Pull request closed without merging**
