### PR TITLE
fix: Popover Shadow

### PR DESCRIPTION
**Pull request by ChristianKienle**
This PR fixes the popover body. I have removed the border and changed the box-shadow. Both changes are according to spec as far I know.

### CODE REVIEW

**Comment by droshev** [comment]
@LeoT7508 @jeannewalters could you review it? 
https://deploy-preview-1472--fundamental.netlify.com

**Comment by ChristianKienle** [comment]
I will fix the CI issues today. :D

**Comment by LeoT7508** [comment]
@droshev 

This link doesn't take me to the component.

**Comment by ChristianKienle** [comment]
> @droshev
> 
> This link doesn't take me to the component.

@LeoT7508 There should be a side navigation on the left that allows you to navigate to the "Popover" page. For your convenience: https://deploy-preview-1472--fundamental.netlify.com/components/popover.html

**Comment by saad-mo** [comment]
@ChristianKienle please fix tests by running `npm run test:update` so this PR can be merged

**Comment by saad-mo** [comment]
repopend a new PR for this changes here - #1507

**Pull request closed without merging**
