### PR TITLE
feat: add no-icon modifier for alert to match UI Kit v1.4.3 

### PR DESCRIPTION
**Pull request by saad-mo**
Closes sap/fundamental#1492

adds `no-icon` modifier to render `information`, `success`, `warning` and `error` without an icon

Screen Shot 2019-06-14 at 10 08 44 AM

#### Test

* http://localhost:3030/alert
* http://127.0.0.1:4000/components/alert.html

#### Changelog

**New**

* `no-icon` modifier

**Changed**

nothing

**Removed**

nothing

### CODE REVIEW

**Comment by droshev** [comment]
@saad-mo can you cherry pick this in `fundamental-styles` too once you align with Leo?

**Comment by saad-mo** [comment]
@LeoT7508 updated the icon and close button size. it was indeed bigger. 

https://deploy-preview-1493--fundamental.netlify.com/components/alert.html

**Comment by saad-mo** [comment]
> It looks like the height of these are off, looks like it might be 38px, it should be 40px tall. The close icon looks right.

height on a single line alert updated to 40px - https://deploy-preview-1493--fundamental.netlify.com/components/alert.html

**Comment by saad-mo** [comment]
> It looks like the icons are now not centered vertically.
> 
> Screen Shot 2019-06-25 at 9 47 29 AM

fixed. 

Screen Shot 2019-06-26 at 2 40 30 PM

**Pull request merged**
