### PR TITLE
#501  Bug: Forms

### PR DESCRIPTION
**Pull request by saadmhybris**
Closes sap/fundamental#501

Fixes various form issues listed in the ticket #501

#### Test

* http://localhost:3030/form
* http://localhost:3030/dropdown

#### Changelog

**New**

nothing 

**Changed**

* Style for from select 
* Style for drop-down component 
* change messaging icons to sap icons 
* various color updates to match the design sheet

**Removed**

nothing

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit e20d88fcee5af2fe7e7e12e9633f8c2c59b924ed

https://deploy-preview-599--fundamental.netlify.com

**Comment by LeoT7508** [comment]
@saadmhybris 

A handful of changes are needed. 

Input fields:

- [ ] Hover state color is incorrect, please refer to this design sheet for details:

**Comment by saadmhybris** [comment]
@LeoT7508 all changes are done. Please review again. 

For your question regarding the help, the popover component is different than the help popover. help popover is baked into the form fields whereas the popover is just a mechanism  that can be used with buttons and menus

**Comment by LeoT7508** [comment]
@saadmhybris 

This looks good from the visual side. Nice work 👍🏽

**Comment by saadmhybris** [comment]
Ready for code review.

**Pull request merged**
