### PR TITLE
Feature/525

### PR DESCRIPTION
**Pull request by xak**
Closes sap/fundamental#525

> Wizard and tab-editor are N/A at this time.

Introduces `hover` and `pressed` variables and and applies them to applicable interactive elements. Adds functions to darken other colors, e.g, status colors of buttons.

**Vars**
- `$fd-link-color--hover`: darkens `action-1` for a hover state
- `$fd-link-color--pressed`: darkens `action-1` for a pressed state

**Functions**
- `fd-color-darker($color)`: applies same darken formula as the hover state
- `fd-color-darkest($color)`: applies same darken formula as the pressed state

#### Test

In branch `feature/525`

Colors apply to 
* http://localhost:3030/button
* http://localhost:3030/button-group
* http://localhost:3030/form
* http://localhost:3030/input-group
* http://localhost:3030/toggle

#### Changelog

**New**

* Adds `$fd-link-color--hover` and `$fd-link-color--pressed` SASS variables for pseudo states
* Adds `fd-color-darker($color)` and `fd-color-darkest($color)` SASS functions to transform additional colors

**Changed**

* Changes `fd-toggle` sizes to align with other notations, now size modifiers are `fd-toggle--xs`, `fd-toggle--s`, and `fd-toggle--l`
* Fixes CSS vars which were not being output properly
* Moves color SASS functions to new `functions/_color.scss` file
* Adjusts padding to the left of an input text field

screen shot 2018-07-06 at 8 10 47 atm

* Refactors `fd-toggle` to remove the left and right padding to better align when stacked with other fields

screen shot 2018-07-06 at 8 12 45 atm

* Changes `active` and `pressed` states for `--toolbar`, `--negative`, and `--positive` buttons
* Adds a white background to form input fields
* Adds param to test environment `format` method to pass a background color, e.g., `{{ format(example,"white") }}`

screen shot 2018-07-06 at 8 01 25 atm

**Removed**

* Nothing

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit bac133d35eec9f8d38c644b4019793ed5f1b00eb

https://deploy-preview-527--fundamental.netlify.com

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit ac9bf403fa21d7c2b6f450b89ea72422713bd8ea

https://deploy-preview-527--fundamental.netlify.com

**Comment by saadmhybris** [comment]
@xak This PR has conflicts.

**Comment by LeoT7508** [comment]
@xak 

**Buttons**: Look good 👍🏽

**Button Group**: Look good 👍🏽

**Form**: One small note, for Select box there seems to be inconsistency with the chevron icon: 
screen shot 2018-07-06 at 9 54 22 am
screen shot 2018-07-06 at 9 54 42 am

**Also for Form**, this information should be bolded:
screen shot 2018-07-06 at 9 55 33 am

**Input Group**: There seems to be more inconsistency with the icons here, are we using the SAP Icon font for these examples? Other than that this is good 👍🏽

**Toggle**: The on states look right here 👍🏽, but the idle states are still not correct. The colors for the shapes are still outdated, the outline for the circle, the circle, and the long shape behind the circle should match what's here: https://zpl.io/adAqADp

**Comment by xak** [comment]
@LeoT7508 I adjusted the toggle colors ...

screen shot 2018-07-06 at 1 08 15 ptm

The other items you point out were not in the scope of this issue which was just about the colors. Please open a new issue to cover the icon and bold items.

**Comment by LeoT7508** [comment]
@xak @saadmhybris 

Stuff looks good from the design side. Thanks fellas.

**Pull request merged**
