### PR TITLE
docs: add new call to action

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Closes sap/fundamental#1570

Adds a call to action for the landing page

### CODE REVIEW

**Comment by jessmetivier** [comment]
Hey stefano, please check out all the content and switch the text to the updated ones.

Also the grey container's bottom has too much padding. The padding looks off for the buttons too, especially on the left and right sides.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey stefano, please check out all the content and switch the text to the updated ones.

Also the grey container's bottom has too much padding. The padding looks off for the buttons too, especially on the left and right sides.

**Comment by jessmetivier** [comment]
Another note: pay attention to where the text breaks, those line breaks should be deliberate. 
Screen Shot 2020-10-30 at 9 03 04 AM
The pauses in our speech should be mimicked in our design, especially for the desktop version where we have the space to achieve that. We can go over it in a call if you need more clarification :)

**Comment by stefanoScalzo** [comment]
> Hey stefano, please check out all the content and switch the text to the updated ones.
> 
> Also the grey container's bottom has too much padding. The padding looks off for the buttons too, especially on the left and right sides.

Padding is 8px in between buttons and the sections all share a 140px padding

**Comment by jessmetivier** [comment]
1. What I meant is that there is more padding inside the button between the text and the left and right sides of the text (35px). Is it 35px padding?

Your implementation:
Screen Shot 2020-10-30 at 2 20 49 PM

The design:
Screen Shot 2020-10-30 at 2 21 28 PM

2. The padding of the grey container is very visibly off, how can that be if they are the same padding all the way around? If anything the line-height of the text would make the top area more spacious than the bottom.
Screen Shot 2020-10-30 at 2 22 54 PM

**Comment by jessmetivier** [comment]
Oh, and if there is no color in the secondary button. Why did you add it?

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Please see comments

**Comment by jessmetivier** [comment]
Last thing, great job with the button interaction states 👍🏼

**Comment by jessmetivier** [comment]
Hey, hey.

**Mobile view (iPhone 5/SE)**
1. The padding between the text and the grey content container should only be 44px.
2. Text in secondary button is wrapping in the iPhone 5/SE view (320px).
Screen Shot 2020-11-02 at 11 27 49 AM


**Desktop (1024px to 1439px)**
1. "What's in the UI kit bundle" is still there.
2. The text of the H3 headers is the same as the text underneath, creating very little hierarchy between them except a slight change in weight. Please follow the Desktop design in Sketch/Zeplin.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Please see comments

**Comment by stefanoScalzo** [comment]
> Please see comments

fixed

**Comment by jessmetivier** [comment]
Hey stefano, thanks for making the changes.

It still seems like there's a lot of padding between the CTA section and the UI kit details:
Screen Shot 2020-11-04 at 9 42 37 AM

There should only be 44 px.

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Hey stefano, thanks for making the changes.

It still seems like there's a lot of padding between the CTA section and the UI kit details:
Screen Shot 2020-11-04 at 9 42 37 AM

There should only be 44 px.

**Comment by stefanoScalzo** [comment]
> Hey stefano, thanks for making the changes.
> 
> It still seems like there's a lot of padding between the CTA section and the UI kit details:
> Screen Shot 2020-11-04 at 9 42 37 AM
> 
> There should only be 44 px.

fixed

**Comment by jessmetivier** [comment]
Looks great, only thing that looks off to me is the padding between the text and the buttons. Is it 20px?

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Please see comments

**Comment by stefanoScalzo** [comment]
fixed

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Button sizes look too large:
Screen Shot 2020-11-10 at 9 45 25 AM

This is what they're supposed to look like:
Screen Shot 2020-11-10 at 9 44 53 AM

Are the buttons 44px high, and have 35px padding from left-right, and 12px from the top to bottom from the text?

**Comment by stefanoScalzo** [comment]
> Button height looks too high:
> Screen Shot 2020-11-10 at 9 45 25 AM
> 
> This is what they're supposed to look like:
> Screen Shot 2020-11-10 at 9 44 53 AM
> 
> Are the buttons 44px high, and have 35px padding from left-right, and 12px from the top to bottom from the text?

fixed

**Review by jessmetivier — APPROVED** [review]
Great job!

**Review by droshev — APPROVED** [review]

**Pull request merged**
