### PR TITLE
fix: renaming private scss files

### PR DESCRIPTION
**Pull request by jbadan**
This is prerequisite work for moving to a new `node-sass` and `post-css` build pipeline. 

These files are currently not the in the `dist` folder, renaming them with an underscore will prevent them from being picked up by node-sass. Note: the imports of these files do not need to be updated, see`core.scss` as an example. `@import "core/root"` works the same as `@import "core/_root"`

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit aec5b853ee46b904bf883ba7fa2e75d994894717

https://deploy-preview-1379--fundamental.netlify.com

**Comment by bcullman** [comment]
Seems like the references to these files should also be renamed. 

I get that SCSS may allow for `name` -> `_name` substitution, but I think that is not intuitive.

**Comment by bcullman** [comment]
After further discussion with @jbadan, we have determined that it is common in SASS to import  `.scss` without the underscore or even the file extension.

for example, see: https://github.com/twbs/bootstrap/blob/master/scss/bootstrap.scss

So, disregard my prior comment.

**Comment by eboyer** [comment]
@bcullman @jbadan ~ Just to confirm then, @jbadan's original statement of references not being needed to be updated still holds true?

**Comment by bcullman** [comment]
@eboyer correct.

**Pull request merged**
