### PR TITLE
Add mobile support in docs site - #1104

### PR DESCRIPTION
**Pull request by ckoutsiaris**
Closes sap/fundamental https://github.com/SAP/fundamental/issues/1104

With js was the easiest/quickest  way to add some basic support for mobile devices. I need to spend some more time on it in the future in order to achieve the same with css.

#### Test

* http://localhost:4000/

mobile-small mov

### CODE REVIEW

**Comment by joseegm** [comment]
Test Version for this PR was deployed

Built with commit 953bb1b0f9d821d35d791d84ceb52127df22190c

https://deploy-preview-1154--fundamental.netlify.com

**Comment by saadmhybris** [comment]
@ckoutsiaris This is good but, it's kind of awkward when resizing the window. The main goals described in #1104 is to make it responsive and not necessirilay mobile compatible. Is it possible to achieve this with css rather than JS?

**Comment by ckoutsiaris** [comment]
@saadmhybris yes I agree, I want to do it with media queries but only that won't be enough. Eg. the sidenav button on the header needs to appear only in specific routes so we have to use a little js.
As I said in the PR comment this was the quickest way since we don't have mobile support at all at the moment. I'll continue to work on this story.

PS. After resizing the window if you refresh it should work. I suppose it is more of an adaptive approach rather than responsive.

**Comment by ckoutsiaris** [comment]
Hi, @saad-mo I redid everything with media queries. Can you please check again.

**Pull request merged**
