### PR TITLE
fix: Updates to colors

### PR DESCRIPTION
**Pull request by eboyer**
Closes sap/fundamental#1387

Putting this one up for review/discussion, hold on merging for a bit.

### CODE REVIEW

**Comment by eboyer** [comment]
@LeoT7508 ~ Color updates, for review: https://deploy-preview-1416--fundamental.netlify.com/foundation/colors.html

I have a suspicion not everything is 100% accurate between hex values and HSL values in the doc. My gut feel is that MOST HSL values are correct, but for example white - #ffffff - is defined two different ways.

For hex values, the reason why I say that is because there were a handful of instances where HSL values changed, but hex values did not at all. 

All that said, can you go color by color in the URL above and confirm both the hex and HSL values are 100% accurate and point out any discrepancies you may see?

**Comment by droshev** [comment]
@eboyer i can confirm the hsl and rgb are not in sync at all. I wouldn't touch the colors until everything is final. I would say changing colors now may require revisiting the more thoroughly later.

**Comment by LeoT7508** [comment]
@eboyer @droshev 

We need to update these colors to be in sync with each other, whether or not they are aligned with what GD is iterating on isn't important. All our documentation should match as closely as possible. All the design assets have updated colors. We need to move forward with those colors.

**Comment by LeoT7508** [comment]
@eboyer 

I went through each color and checked the HSL values for each to make sure they match. On our side we should be good to go. We might not match GD exactly right at this moment with any changes they are making but at least our team and our assets will be in sync. Let me know if theres anything else we need to get this pushed through. 

A couple questions about the colors you updated. 

Action 3 (#0854A1) - That number and color don't exist in the color palette anymore. 
Background 1 - The value is incorrect, it should be #F7F7F7
Background 3 - The value is incorrect, it should be #f1fdf6
Neutral 2 - The value is incorrect, it should be #EDEDED
Status 4 - The value is incorrect, it should be #6D7678
Accent 9 - The value is incorrect, it should be #925ACE
- You can drop Accent 11-15, GD got rid of those. 
State Action Hover - The value is incorrect, it should be #0854A0

**Comment by eboyer** [comment]
Closing this PR for now, until we dig in to exactly what needs to happen with the next color update(s).

**Pull request closed without merging**
