### PR TITLE
docs: add testemonials

### PR DESCRIPTION
**Pull request by stefanoScalzo**
Closes sap/fundamental#1554

Add testimonials section

### CODE REVIEW

**Comment by droshev** [comment]
We need to rethink the current approach
Screen Shot 2020-08-25 at 6 21 49 PM

**Comment by jessmetivier** [comment]
Hi @stefanoScalzo,

As per our discussion today:

I think since we don't have any more testimonials, this is the best design. The arrow buttons will be a better transition/functionality than the dots (too small to click on/too sudden when they transition).

**WEB**
Screen Shot 2020-09-15 at 6 55 52 PM

**MOBILE**
Screen Shot 2020-09-15 at 6 29 21 PM


We can apply the max character count, and have a minimum character count for testimonial submissions. I still believe that we can _feature_ (select) them in the future, so in the long run we don't have to showcase every testimonial on the landing page... No site does that. And the testimonials that meet the requirements will make the cut, simply put.

For when the user clicks on "Read more", the text area will increase downward but the arrow buttons should not move, otherwise it will throw the users off. Nothing in that section should move other than the text area when expanded, and possibly the size of the logo if they slightly differ in proportions.

The background image: https://sap.sharepoint.com/:i:/s/85000030/ESrqBZ91ctdLn1CDDeX7WSkBrevnq7fA1PswjMHjk-Whhg?e=D7N8FG (Opacity 55%)

I've added you to the Zeppelin files here: zpl.io/25LyRrQ

**Review by jessmetivier — CHANGES_REQUESTED** [review]
See conversation thread

**Comment by jessmetivier** [comment]
Hey stefano,

The arrow functionality is great!

A few things:
- The arrow on the right looks too far because its centering the arrows with the text only and not including the quotation, check out the spacing in this image:
Screen Shot 2020-09-29 at 12 45 17 PM
- The background image isn't rendering
- The fade in-out between the testimonials is too fast, I suggest 5 seconds until the fade.
- Like we discussed last time, let's try to achieve Show more/Show less embedded into the text.
Here's an example of thread that might help!
https://stackoverflow.com/questions/52367723/ellipses-after-excerpt-and-read-more?rq=1

**Comment by stefanoScalzo** [comment]
> Hey stefano,
> 
> The arrow functionality is great!
> 
> A few things:
> 
> * The arrow on the right looks too far because its centering the arrows with the text only and not including the quotation, check out the spacing in this image:
> 
> Screen Shot 2020-09-29 at 12 45 17 PM
> 
> - The background image isn't rendering - The fade in-out between the testimonials is too fast, I suggest 5 seconds until the fade. - Like we discussed last time, let's try to achieve Show more/Show less embedded into the text. Here's an example of thread that might help! https://stackoverflow.com/questions/52367723/ellipses-after-excerpt-and-read-more?rq=1

I've added swipe functionality, extended the length and adjusted the right margin of the text visually. The read more has to be on a different line as the elipses

**Comment by jessmetivier** [comment]
Hey Stefano!

The recent PR looks great, but there are still quite a few issues:

1. The spacing is still off between the text, the word "They" should have gone to the other line in the photo below:
Screen Shot 2020-09-30 at 2 54 23 PM

Maybe the blue container could be a shorter from the right side:
Screen Shot 2020-09-30 at 3 06 19 PM

2. This is what the arrows look like from the mobile view:
Screen Shot 2020-09-30 at 2 59 00 PM

3. The heading hierarchy is off at different breakpoints for the new sections (Design & Testimonials), look at the difference between "Testimonial" and "Community"
Screen Shot 2020-09-30 at 2 56 25 PM

4. The distance between the text and the background should be the same:
Screen Shot 2020-09-30 at 3 20 09 PM

5. The interaction could be a little bit more friendly. When the user is reading the testimonial, and decides to click "Show more" to read the rest, it shouldn't change to the next testimonial. It should stop completely and when they decide to go to the next one, they'll use the arrows.

Let me know what you think, and if you have any questions. We could meet to go over it :)

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Check out latest comment in conversation

**Comment by stefanoScalzo** [comment]
> Check out latest comment in conversation

Fixed!

**Comment by jessmetivier** [comment]
As per our slack call, just waiting for the image shift issue to be resolved before merging.

**Review by jessmetivier — APPROVED** [review]
Looks great!

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Need to fix mobile version, because changes were made and need to be assessed.

**Comment by jessmetivier** [comment]
The web looks fantastic Stefano!

But please follow the design as closely as possible:
Screen Shot 2020-10-07 at 12 04 28 PM

1. Place arrows more toward the edges, and make the clickable area larger. This is to achieve visual design without interrupting functionality. The user will still have no issues pressing the arrow buttons.

2. Left align the text

3. Change the text to "View more", to align with future content.

4. Change SAP Fieldglass logo: https://www.google.com/search?q=SAP+fieldglass+logo+transparent&tbm=isch&ved=2ahUKEwir3bTV7qLsAhXIGN8KHQhuCJUQ2-cCegQIABAA&oq=SAP+fieldglass+logo+transparent&gs_lcp=CgNpbWcQAzICCAA6BAgAEB5Q1zpY9UlguUtoAHAAeACAAWWIAewHkgEEMTEuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=1Od9X6ujCsix_AaI3KGoCQ&bih=869&biw=1860#imgrc=QQ7hoDSXOgKvOM

**Comment by stefanoScalzo** [comment]
> The web looks fantastic Stefano!
> 
> But please follow the design as closely as possible:
> Screen Shot 2020-10-07 at 12 04 28 PM
> 
> Right now it looks awkward mostly because the quote's text needs room to breathe:
> Screen Shot 2020-10-07 at 12 10 14 PM
> 
> 1. Place arrows more toward the edges, and make the clickable area larger. This is to achieve visual design without interrupting functionality. The user will still have no issues pressing the arrow buttons.
> 2. Left align the text
> 3. Change the text to "View more", to align with future content.
> 4. Change SAP Fieldglass logo: https://www.google.com/search?q=SAP+fieldglass+logo+transparent&tbm=isch&ved=2ahUKEwir3bTV7qLsAhXIGN8KHQhuCJUQ2-cCegQIABAA&oq=SAP+fieldglass+logo+transparent&gs_lcp=CgNpbWcQAzICCAA6BAgAEB5Q1zpY9UlguUtoAHAAeACAAWWIAewHkgEEMTEuMZgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=1Od9X6ujCsix_AaI3KGoCQ&bih=869&biw=1860#imgrc=QQ7hoDSXOgKvOM

Fixed, the button shouldn't be full width, its taking to much focus away from the testemonial

**Comment by jessmetivier** [comment]
Hey Stefano, it's really starting to shape up.

As we discussed, let's change the button to text instead like this:

**WEB**
Screen Shot 2020-10-09 at 9 36 03 AM

**MOBILE**
Screen Shot 2020-10-09 at 9 30 08 AM



Right now the mobile has a few kinks that need to be ironed out:

1. Logo is way too large here, logo sizes need to be consistent across testimonials. Can you bring the SAP Fieldglass logo down to the size of the SAP FSM logo?
Screen Shot 2020-10-09 at 9 29 57 AM

2. "View more" should be closer to the text, not close to the logo. Try placing it right underneath like in the design (no pixel spacing). Then the logo can move up slightly but show a clear space between the logo and the text (16px).
Screen Shot 2020-10-09 at 9 51 42 AM

3. I noticed the text width changes from one testimonial to the other. Their width should stay the same. 
Screen Shot 2020-10-09 at 9 29 57 AM

**Comment by jessmetivier** [comment]
Hi Stefano,

Regarding your recent merge:

Screen Shot 2020-10-09 at 11 34 11 AM
1. Close the gap here, that way the logo in the next testimonial won't seem so far down.
2. Change the text color to #767676
3. It's missing a period at the end of the sentence (make sure it's the grey color and not part of the link) ;)
4. You won't believe this but... the background image is shifting on the web view again.
5. Also, this.
Screen Shot 2020-10-09 at 11 53 08 AM

**Review by jessmetivier — CHANGES_REQUESTED** [review]
Ch-Ch-Ch-Changes!

**Comment by stefanoScalzo** [comment]
> Ch-Ch-Ch-Changes!

Should be good now I triple checked everything and added fixes for iPad so now it'll be good

**Comment by jessmetivier** [comment]
Hey Stefano, it looks really awesome!

Just a few things:
1. The heading sizes are not the same across headers between the mobile and XL size (I believe). Keep all the headers at 48px in between, then bump them up to 54px for XL.
Screen Shot 2020-10-13 at 1 41 52 PM

2. The period is still missing at the end of "Add your company's testimonial"(**period - in #767676 color**)

3. The proximity of the logo to the text doesn't look good here. Anyway to space this out more? Maybe even add a "View less" control?

**Review by jessmetivier — CHANGES_REQUESTED** [review]
minor things

**Comment by stefanoScalzo** [comment]
> Hey Stefano, it looks really awesome!
> 
> Just a few things:
> 
> 1. The heading sizes are not the same across headers between the mobile and XL size (I believe). Keep all the headers at 48px in between, then bump them up to 54px for XL.
> 
> Screen Shot 2020-10-13 at 1 41 52 PM
> 
> 1. The period is still missing at the end of "Add your company's testimonial"(**period - in #767676 color**)
> 2. The proximity of the logo to the text doesn't look good here. Anyway to space this out more? Maybe even add a "View less" control?
> 
> Screen Shot 2020-10-13 at 1 37 54 PM

fixed

**Comment by jessmetivier** [comment]
The "View less" control works great, and fixes the proximity issue!

Just a couple things I noticed: 
1. The distance between the top and bottom are not aligned (I believe this is in the tablet size)
Screen Shot 2020-10-14 at 1 15 35 PM

2. The spacing between the text and the logo are a little too far from each other. The design has 64px for the desktop, is that what it is here?
Screen Shot 2020-10-14 at 1 27 33 PM
Ping me on slack, and we can determine a good distance.

**Comment by jessmetivier** [comment]
Last thing:

After looking it over — the last text that says "Have an experience you'd..." needs to be left-align with the first text in Mobile/Tablet view.

It should only be center-aligned in Desktop view (L-XXL) when there is lots of space.
Once the screen size goes down to Tablet/Mobile, the text with the link should truncate to the next line and move to the left. Refer to the Mobile design to see what I mean.

**Review by jessmetivier — APPROVED** [review]
MARVELOUS!

**Review by droshev — APPROVED** [review]

**Pull request merged**
