### PR TITLE
fix: update popover shadow

### PR DESCRIPTION
**Pull request by saad-mo**
This is PR contains changes added by @ChristianKienle in #1472. Recreating this as external contributors cannot fix VRT

---
Original PR comments 

> This PR fixes the popover body. I have removed the border and changed the box-shadow. Both changes are according to spec as far I know.

#### Test

* http://localhost:3030/popover

#### Changelog

**New**

nothing

**Changed**

* border on popover. slight changes in color and shadow

**Removed**

noting

### CODE REVIEW

**Comment by ChristianKienle** [comment]
> @saad-mo
> 
> All the popover shadows should be the same. @SaiShan and I did some work on the popover shadow for date picker. The styles should be the same across all components for consistency. Do you wanna sync up and get these aligned?

It is my understanding that components like dropdown/… are just using the popover component. Thus the shadow should be the same across all components. Right?

**Comment by LeoT7508** [comment]
The shadows should always be consistent unless otherwise documented in the design sheets.

**Comment by ChristianKienle** [comment]
> The shadows should always be consistent unless otherwise documented in the design sheets.

I know. But how does this PR make them inconsistent? I don't see it. Sorry. :)

**Comment by LeoT7508** [comment]
@ChristianKienle 

If @SaiShan updated the shadow or the date picker popover it should have cascaded down to every other instance, if it didn't then it's not all the same. You guys should sync up and see if that is correct.

**Comment by saad-mo** [comment]
> @ChristianKienle
> 
> If @SaiShan updated the shadow or the date picker popover it should have cascaded down to every other instance, if it didn't then it's not all the same. You guys should sync up and see if that is correct.

There is only one popover component other components just it. if the drop shadow in this PR is correct, then we can merge this and call it a day.

**Comment by LeoT7508** [comment]
@saad-mo 

This shadow doesn't look the same as the one @SaiShan worked on. Can you guys sync up and align with what she did? This shadow is a lot bigger and has a large spread than the one we adjusted.

**Comment by saad-mo** [comment]
If this change is not accurate and it has already been addressed, then let's just close the PR

**Comment by ChristianKienle** [comment]
FYI: I took the values for the shadow from the Sketch-file…

**Comment by LeoT7508** [comment]
@ChristianKienle 

Like I've explained several times, @SaiShan and I worked on this together, adjustments were made, what's she has is correct...

**Comment by ChristianKienle** [comment]
@LeoT7508 
Can you show me the correct shadow or those adjustments? I would love to know the difference – I never want to stop learning new things.

**Comment by LeoT7508** [comment]
Again, ShaiShan can teach you all you like. Reach out and see how that code looks.

**Pull request closed without merging**
