### PR TITLE
feat: split button implementation

### PR DESCRIPTION
**Pull request by saad-mo**
Closes sap/fundamental#954

Split button with popover menu

#### Test

* http://localhost:3030/button-split
* http://localhost:4000/components/button.html (bottom of the page)

#### Changelog

**New**

* split button with a options menu 

**Changed**

nothing

**Removed**

nothing

### CODE REVIEW

**Comment by jbadan** [comment]
With the expanded testing suite you'll need to run `npm run test:update` whenever you add new examples to the playground. It is automatically grabbing every example it finds and looking for a matching screenshot :)

**Comment by droshev** [comment]
The markup looks a but too much for me. Is there a way to simplify it?
```
<div class="fd-popover fd-contextual-menu fd-has-margin-small">
  <div class="fd-button-split" role="group" aria-label="Split Button example">
    <button class="fd-button--emphasized sap-icon--cart" aria-label="button">Button</button>
    <button class="fd-button--emphasized sap-icon--slim-arrow-down" aria-controls="0T1zk179" aria-haspopup="true" aria-expanded="false" aria-label="More"></button>
  </div>
  <div class="fd-popover__body fd-popover__body--no-arrow fd-popover__body--right" aria-hidden="true" id="0T1zk179">
    <nav class="fd-menu">
      <ul class="fd-menu__list">
        <li><a role="button" class="fd-menu__item">Add to list</a>
        </li>
        <li><a role="button" class="fd-menu__item">Save for later</a>
        </li>
      </ul>
    </nav>
  </div>
</div>
```

**Comment by droshev** [comment]
Screen Shot 2019-05-16 at 8 36 53 PM
tiny alignment issue

**Comment by saad-mo** [comment]
> Is there a way to simplify the markup?
this is a composite component made up of `button` and `popover`. we don't want to modify any markup. 

>I think the popover should be only for the menu and not for the first part of the button?
I tried wrapping popover for just the button, but this was creating alignment issues... let me try one more time. 

> tiny alignment issue
please note that popover menu is right aligned with the button. the menu with is not 100% as the width of the button can change based on the label.

**Comment by droshev** [comment]
look at https://sap.github.io/fundamental/components/dropdown.html
We have already working markup

```
   <div class="fd-popover">
      <div class="fd-popover__control">
         <button class="fd-dropdown__control fd-button  " aria-controls="h0C6A325"
         aria-expanded="false" aria-haspopup="true">
         Select
         </button>
      </div>
      <div class="fd-popover__body fd-popover__body--no-arrow"  aria-hidden="true" id="h0C6A325">
         <nav class="fd-menu">
            <ul class="fd-menu__list">
               <li><a href="#" class="fd-menu__item">Option 1</a></li>
               <li><a href="#" class="fd-menu__item">Option 2</a></li>
            </ul>
         </nav>
      </div>
   </div>
```

**Comment by saad-mo** [comment]
@droshev - 

- simplified markup a bit popover wrapper was not required so removed
- menu width is not 100% of the split-button

**Comment by droshev** [comment]
We can even avoid the second button by applying the `dropdown` pattern with modified coloring of the right button.

**Comment by saad-mo** [comment]
that won't work because the button needs to have a primary action which is the first button and the split /dropdown contains additional options.

**Comment by jbadan** [comment]
@saad-mo The DS_Store one made it in here too - we should troubleshoot why that's being generated at all. We could set it to exclude automatically, but I'm not sure why it's even getting made. It _should_ only be grabbing things inside `#example-container`

**Comment by saad-mo** [comment]
@jbadan I removed the file from this PR.

The file gets generated every time I run `test:update`. not sure why...

**Comment by bcullman** [comment]
@saad-mo add it to `.gitignore`

**Comment by droshev** [comment]
the border of the second button is bigger than the first:
Screen Shot 2019-05-20 at 5 55 19 PM
Screen Shot 2019-05-20 at 5 55 10 PM

**Comment by saad-mo** [comment]
@droshev 

that extra border is due to the active state of the button. we'll have to address it in a separate ticket when updating buttons.

**Pull request merged**
